# Variational calculus

In this section we will introduce the fundamentals of variational calculus. This subject is fundamental in classical mechanics and field theories. It is also at the heart of the finite element method (FEM) for solving partial differential equations. For those interested in the former, the books by @Goldstein2001 and @Tong2025v1 are excellent resources. For the latter, the use of variational principles in the context of FEM is well covered in @Langtangen2019.

These notes are intended to be self-contained and present as little details as possible, so pen and paper is recommended to follow the derivations, or if you prefer, SymPy is well suited for symbolic calculations and can be used to verify the results. Focus will be given to the ideas as discussed in the more physical of the aforementioned books by @Tong2025v1 and @Goldstein2001. These are confronted as each provides some complementary insights on *how to think* about the problem.

The main element of variational calculus is the concept of a functional. While a function $f$ maps a number to another number, $f(x):{}\Re\to\Re$, a functional $F$ is a mapping from a function to a number, $F[f(x)]:{}(\Re\to\Re)\to\Re$. Such mapping can be achieved through integration of $f$ over a domain. The main interest of doing so is to seek for a function that establishes a stationary point of the functional, what ultimately leads to the Euler-Lagrange equations.

## External resources

- [Calculus of Variations (Faculty of Khan)](https://www.youtube.com/playlist?list=PLdgVBOaXkb9CD8igcUr9Fmn5WXLpE8ZE_)
- [The Calculus of Variations and the Euler-Lagrange Equation (Xander Gouws)](https://www.youtube.com/watch?v=V0wx0JBEgZc&t=237s)
- [Minimization In Infinite Dimensions With The Calculus Of Variations (Dr. Simulate)](https://www.youtube.com/watch?v=F8c1Sp2A8QE)
- [Finite differences in SymPy](https://docs.sympy.org/latest/explanation/special_topics/finite_diff_derivatives.html)
- [Taylor Series in Multiple Variables (Wikipedia)](https://en.wikipedia.org/wiki/Taylor_series#Taylor_series_in_multiple_variables)

```{python}
from sympy import *
```

## Euler-Lagrange equations

-   Multivariate Taylor series expansion:

$$
f(x+\delta{x}, y+\delta{x}) = f(x, y) +
\frac{\partial{f}}{\partial{x}}\delta{x} +
\frac{\partial{f}}{\partial{y}}\delta{y} +
\mathcal{O}(\delta{x}^{2}+\delta{x}^{2})
$$

-   Finding functional extrema, $\delta{F[f(x)]} = F[y+\delta{y}] - F[y] = 0$:

$$
F[y+\delta{y}] - F[y] =
\int_{}dx\;L(y+\delta{y}, y^{\prime}+\delta{y^{\prime}},x)-
\int_{}dx\;L(y, y^{\prime},x)
$$

$$
L(y+\delta{y}, y^{\prime}+\delta{y^{\prime}},x)=
L(y, y^{\prime},x) +
\frac{\partial{L}}{\partial{y}}\delta{y} +
\frac{\partial{L}}{\partial{y^{\prime}}}\delta{y^{\prime}}
$$

$$
F[y+\delta{y}] - F[y] =
\int_{}dx\;\left(
    \frac{\partial{L}}{\partial{y}}\delta{y} +
    \frac{\partial{L}}{\partial{y^{\prime}}}\delta{y^{\prime}}
\right)
$$

<!-- The main idea is to find the function that minimizes (or maximizes) a given functional, which is a mapping from a space of functions to the real numbers. This is often done by finding the stationary points of the functional, which leads to the Euler-Lagrange equations. -->

```{python}
def univariate_taylor_expansion(f, x, order=2):
    pass

def multivariate_taylor_expansion(f, x, order=2):
    pass

```

```{python}
x, x0, h = symbols('x, x_0, h')
Fi, Fip1, Fip2 = symbols('F_{i}, F_{i+1}, F_{i+2}')

n = 3 # there are the coefficients c_0=Fi, c_1=dF/dx, c_2=d**2F/dx**2
c = symbols('c:3')

def P(x, x0, c, n):
    return sum( ((1/factorial(i))*c[i] * (x-x0)**i for i in range(n)) )

P(Fi, x, c, n)
```

```{python}
c
```

```{python}
n = 1

x = sm.symbols('x')
x = sm.MatrixSymbol('v', n, 1)

y = sm.Function('y')(x)
# ydot = y.diff(x)
ydot = sm.Derivative(y, x)
L = sm.Function('L')(y, ydot, x)
# sm.Derivative(L, y).series(y)
```

```{python}
# L = sm.Function('L')(y, ydot, x)
# L.diff(y)

# L.series(x, 0, 2)
# L.series(ydot, 0, 2)
```


```{python}
import sympy as sp

def taylor_multivariate(expr, vars, point, order):
    """
    Multivariate Taylor expansion of expr around point up to total degree < order.
    vars  : tuple of variables (x, y, ...)
    point : tuple of expansion point (a, b, ...)
    order : total degree cutoff
    """
    # Shift variables: u_i = x_i - a_i
    shifts = {v: v0 + sp.Symbol(f"d{v.name}") for v, v0 in zip(vars, point)}
    inv_shifts = {sp.Symbol(f"d{v.name}"): v - v0 for v, v0 in zip(vars, point)}
    
    expr_shifted = expr.subs({v: inv_shifts[sp.Symbol(f"d{v.name}")] for v, v0 in zip(vars, point)})
    
    # Expand fully
    series = sp.series(expr_shifted, *[(sp.Symbol(f"d{v.name}"), 0, order) for v in vars])
    
    # Remove O(...) terms
    poly = sp.expand(series.removeO())
    
    # Convert to polynomial and filter by total degree
    poly_terms = sp.Poly(poly, [sp.Symbol(f"d{v.name}") for v in vars])
    result = 0
    for monom, coeff in poly_terms.terms():
        if sum(monom) < order:
            term = coeff
            for v, p in zip(vars, monom):
                term *= (v - point[vars.index(v)])**p
            result += term
    
    return sp.simplify(result)

x, y = sp.symbols('x y')
f = sp.exp(x*y) + sp.sin(x + y)

t = taylor_multivariate(f, (x, y), (0, 0), order=4)
print(t)
```


```{python}
def taylor_template(f, vars, point, order):
    """
    Formal Taylor expansion of an arbitrary multivariate function.
    f      : f(x1, x2, ..., xn) as a SymPy Function
    vars   : (x1, x2, ..., xn)
    point  : (a1, a2, ..., an)
    order  : expansion order
    """
    x = vars
    a = point
    subs = {xi: ai for xi, ai in zip(x, a)}

    # 0th order
    result = f.subs(subs)

    # higher orders
    for k in range(1, order+1):
        # all k‑tuples of variables
        for idx in sp.utilities.iterables.multiset_permutations(range(len(x)), k):
            term = 1
            deriv = f
            for i in idx:
                term *= (x[i] - a[i])
                deriv = sp.diff(deriv, x[i])
            result += term * deriv.subs(subs) / sp.factorial(k)

    return sp.simplify(result)

x1, x2, x3 = sp.symbols('x1 x2 x3')
f = sp.Function('f')(x1, x2, x3)

T = taylor_template(f, (x1, x2, x3), (0, 0, 0), order=3)
print(T)
```