#!/usr/bin/env bash

#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
# Manually add the following line to your ~/.bashrc to enable these aliases
# (assuming kompanion was installed in $HOME/kompanion):
#
# if [ -d "${HOME}/kompanion/config/bashrc" ]; then
#     source "${HOME}/kompanion/config/bashrc"
# fi
#
#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

MAJORDOME_GIT="https://github.com/wallytutor/python-majordome.git"

alias majordome="git clone ${MAJORDOME_GIT} majordome"

##############################################################################
# Common aliases
##############################################################################

alias src="source ~/.bashrc"

alias df="df -HT"
alias du="du -h --max-depth=1"

alias ll='ls -Alh --group-directories-first | sort -k9 -V -r'
alias ls="ls -lh --group-directories-first"

##############################################################################
# Container aliases
##############################################################################

pfresh() {
    podman builder prune -a
    podman system prune -a --volumes
}

alias pi="podman image"
alias pc="podman container"

alias pil="podman images -a"
alias pcl="podman container ls"
alias pcp="podman container prune"

alias appi="apptainer instance"
alias appl="apptainer instance list"
alias appx="apptainer instance stop"

# drun() {
#     docker run -it --rm --gpus all \
#         --mount type=bind,source="$(realpath $PWD)",target=/opt/app \
#         "${1}" "${2:-/bin/bash}"
# }

# apu() {
#     apptainer instance start --writable-tmpfs \
#         --bind "$(realpath $PWD):${2:-/opt/app}" "${1}" "${1%.sif}"
# }

pexec() {
    local label=$1

    if [ -z "${label}" ]; then
        echo "Usage: pexec <container-id|container-name>" >&2
        podman container ls
        return 1
    fi

    podman exec -it "${1}" /bin/bash
}

##############################################################################
# Neovim configuration
##############################################################################

NVIM_VER=$(nvim --version | head -n1 | sed 's/^NVIM v//')

# check if >= 0.10
if printf '%s\n' "$NVIM_VER" "0.10" | sort -V | head -n1 | grep -q "0.10"; then
    export XDG_CONFIG_HOME="${SCRIPT_DIR}/../.config"
fi

if command -v nvim >/dev/null 2>&1; then
    alias vi="nvim"
    alias vim="nvim"
fi

##############################################################################
# Screen aliases
##############################################################################

alias scl="screen -ls"
alias scx="screen -x"
alias scs="screen -S"
alias scr="screen -r"

##############################################################################
# Configure fake home of Kompanion
##############################################################################

export IPYTHONDIR="${SCRIPT_DIR}/../.ipython"
export JUPYTER_DATA_DIR="${SCRIPT_DIR}/../.jupyter"
export JUPYTER_PATH="${SCRIPT_DIR}/../.jupyter"
# export VSCODE_EXTENSIONS="${SCRIPT_DIR}/../.vscode/extensions"
# export VSCODE_SETTINGS="${SCRIPT_DIR}/../.vscode/user-data"

##############################################################################
# Sourcing of other configuration files
##############################################################################

# Source Rust
if [ -f "${HOME}/.cargo/env" ]; then
    source "${HOME}/.cargo/env"
fi

# Source OpenFOAM
if [ -f "/opt/openfoam13/etc/bashrc" ]; then
    source "/opt/openfoam13/etc/bashrc"
fi

##############################################################################
# EOF
##############################################################################