project:
  type: book

execute:
  cache:   true
  echo:    false
  warning: false

bibliography: references.bib

book:
  title: "Kompanion"
  author: "Walter Dal'Maz Silva"
  date: "today"
  sidebar:
    style: "docked"
    search: true
    collapse-level: 1

  chapters:
    - index.qmd

    - part: computing/index.qmd
      chapters:
        - computing/git.qmd
        - computing/ssh.qmd
        - computing/coding.qmd
        - computing/vscode.qmd
        - computing/windows.qmd
        - computing/containers.qmd
        - computing/tips.qmd
        - computing/selection.qmd
        - computing/portable.qmd

    - part: elmer/index.qmd
      chapters:
        - elmer/elmer.qmd
        - elmer/sif.qmd
        - elmer/matc.qmd

    - part: fluent/index.qmd
      chapters:
        - fluent/tui-basics.qmd
        - fluent/tui-config.qmd
        - fluent/tui-setup.qmd
        - fluent/tui-solution.qmd
        - fluent/tui-results.qmd
        - fluent/pyfluent.qmd

    - part: "Montagne"
      chapters:
        - tracks/carto.qmd
        - tracks/liens.qmd

    - references.qmd

format:
  html:
    highlight-style: github
    theme:
      - pulse

  pdf:
    highlight-style: github
    documentclass: scrreprt
    papersize: a4
    mainfont: "Latin Modern Sans"
    sansfont: "Latin Modern Sans"
    geometry:
      - margin=25mm
