# Daily Notes {.unnumbered}

## 2026-03-19

Reading @Kee2017, chapter 11 for preparing future development of `majordome_engineering.symbolic`; revisited basic definitions of transport coefficients (viscosity, thermal conductivity, diffusivity) based on classical macroscopic *gradient-based* semi-empirical laws.

$$
f = -\mu\frac{du}{dz} \quad\text{,}\quad
q = -\lambda\frac{dT}{dz} \quad\text{,}\quad
J^{\ast} = -D\frac{dC}{dz}
$$

*Mixture-averaged* properties are not accurate and are correct asymptotically only in some special cases; they also fail to preserve mass-conservation in species equations and require corrective measures. On the other hand, multicomponent properties require solving linear systems and are general.

## 2026-03-20

Code review for `Kompanion`: currently packing all installation and configuration blocks as a single function as it adds little overhead (just test for a few folders) and simplified maintenance. For implementing the goals, perfectionned a few functions and added `[Parameter(Mandatory, Position=0)]` for positional arguments, allowing for less verbose code. Also improved error reporting of failed downloads and added a global debug flag for more verbose output while migrating all installations to `Invoke-HandledInstall`. After some improvements today, the whole of `Kompanion` is being refactored with better error handling.

I am currently investigating a proper way of getting a local file-based database in Rust. Initial candidates are [redb](https://github.com/cberner/redb) and [sled](https://github.com/spacejam/sled), but the former seems more mature. I currently try to understand if I could serialize arbitrary objects with their B-tree approaches.

After so many years of Python, I feel humbled to discover this works (and I no longer need to use a context handler when reading a JSON file anymore!):

```python
conf = Path("path/to/some/file.json")
data = json.loads(conf.read_text())
```

## 2026-03-21

After a few years without using it, it seems that now [.NET SDK](https://dotnet.microsoft.com/en-us/download/dotnet/10.0) is also supported in portable format. This is an opportunity to learn [F#](https://fsharp.org/) and maybe introduce the use of [Python.NET](https://github.com/pythonnet/pythonnet) to `Majordome`. 
