##############################################################################
# Documentation and help at https://quarto.org/docs/books/
#
# Typical commands to use:
# - quarto preview --no-browser
# - quarto render --to pdf
# - quarto render --to html
##############################################################################

project:
  type: book

execute:
  python: "./.venv/Scripts/pythonw.exe"
  cache: true

##############################################################################
# Structure
##############################################################################

book:
  title: "Notes Book"
  author: "Walter Dal'Maz Silva"
  date: "today"
  sidebar:
    collapse-level: 1

  # --------------------------------------------------------------------------
  # THERMODYNAMICS
  # --------------------------------------------------------------------------

    - part: "Thermodynamics and Transport"
      chapters:
      - chap-thermodynamics/converting-nasa-poly.qmd
      - chap-thermodynamics/converting-shomate.qmd
      - chap-thermodynamics/calphad-nitrides.qmd
      - chap-thermodynamics/calphad-iron-nitrogen.qmd
      - chap-thermodynamics/minerals-scraper.qmd
      - chap-thermodynamics/counter-current-pfr.qmd
      - chap-thermodynamics/acetylene-pyrolysis-reactor.qmd
      - chap-thermodynamics/cfd-processing-pyvista.qmd

  # --------------------------------------------------------------------------
  # MODEL PREDICTIVE CONTROL
  # --------------------------------------------------------------------------

    - part: "Model Predictive Control"
      chapters:
        - chap-controls/mpc-multiple-shooting.qmd
        - chap-controls/mpc-boiling-evaporation.qmd
        - chap-controls/mpc-kinetics-part-a.qmd


  # --------------------------------------------------------------------------
  # ELMER CASES
  # --------------------------------------------------------------------------

    # XXX: run simulations locally before including these cases
    # - part: "Elmer Cases"
    #   chapters:
    #     - chap-elmer-cases/conduction-1/index.qmd
    #     # - chap-elmer-cases/conduction-2/README
    #     # - chap-elmer-cases/conduction-3/README
    #     # - chap-elmer-cases/thermomechanical-1/README

  # --------------------------------------------------------------------------
  # SU2 CASES
  # --------------------------------------------------------------------------

    # XXX: run simulations locally before including these cases
    - part: "SU2 Cases"
      chapters:
        - chap-su2-cases/01-compressible_flow-inviscid_bump/case.qmd

  # --------------------------------------------------------------------------
  # SCIENTIFIC PROGRAMMING
  # --------------------------------------------------------------------------

    - part: "Scientific Programming"
      chapters:
        - chap-programming/rust.qmd
        - chap-programming/haskell.qmd
        - chap-programming/julia101.qmd

  # --------------------------------------------------------------------------
  # IMAGE ANALYSIS
  # --------------------------------------------------------------------------

    - part: "Image Analysis"
      chapters:
        - chap-image-analysis/porosity-measurement.qmd
        - chap-image-analysis/metadata-extraction.qmd
