# Working on Windows {#sec-working-on-windows}

## Command line basics

If this is you first time using the command prompt you might be interested by this section. The command prompt (often referred to as *terminal* in Linux world) is your interface to interact with the operating system and many available tools. To learn any useful scientific computing skills it is useful to get a grasp of its use because it is there that we will launch most applications. The illustrations below assume you are working under Windows, but the introductory commands are common to most operating systems.

Now let's launch a terminal. If you are working under VS Code you can use the shortcut to display the terminal `Ctrl+J`; the bottom of your window should display something as

```pwsh-session
PS D:\Kompanion>
```

The start of this line displays you *path* in the system; depending on your configuration that could not be the case and you can ask the OS to give you that with `pwd` (print working directory)

```pwsh-session
PS D:\Kompanion> pwd

Path
----
D:\Kompanion
```

If you are invited to move to directory `src` you may which to use command *change directory*, or `cd` in the system's language

```pwsh-session
PS D:\Kompanion> cd .\bin\
PS D:\Kompanion\bin>
```

Now that you reached your destination, you might be interested at inspecting the contents of this directory, *i.e.* listing its contents; that is done with `ls` as follows

```pwsh-session
PS D:\Kompanion\bin> ls


    Directory: D:\Kompanion\bin


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         1/31/2025  11:11 AM                apps
d-----          2/3/2025   9:19 AM                data
d-----         1/30/2025   2:34 PM                downloads
d-----          2/3/2025  11:50 AM                pkgs
d-----         1/31/2025   9:33 AM                scripts
d-----         1/30/2025   9:58 AM                tests
-a----         1/31/2025   9:33 AM           2697 activate.bat
-a----         1/30/2025   9:58 AM            161 code.bat
-a----         1/30/2025   9:58 AM            132 kode.bat
-a----         1/30/2025   9:58 AM            131 kpip.bat
```

Oops! It was not the directory you wanted to go to! No problems, you can navigate *one-level-upwards* using the special symbol `..` (two dots) and change directory again

```pwsh-session
PS D:\Kompanion\bin> cd ..\docs\
PS D:\Kompanion\docs>
```

This is the minimum you need to know: navigate, know your address, inspect contents.

## Mount a network drive in WSL

Here we assume we will mount drive `Z:` at `/mnt/z`:

```bash
# Create the mount point (if required):
sudo mkdir /mnt/z

# Mount the network drive in WSL:
sudo mount -t drvfs Z: /mnt/z
```

Actually the same procedure can be used to access a SMB drive from within WSL temporarily with:

```bash
sudo mount -t drvfs '\\path\to\smb' /mnt/<mount-point>/
```

For automatic remount, consider adding the following to your `/etc/fstab`

```bash
//path/to/smb /mnt/<mount-point>/ drvfs auto,rw,nosuid,exec,uid=1000,gid=1000 0 0
```

### Finding a process handle

This is useful when Windows won't let you move a file or folder because *it is already open somewhere*. First, download and extract [Handle](https://learn.microsoft.com/en-us/sysinternals/downloads/handle); from PowerShell run the following:

```bash
./handle.exe -u -nobanner "C:\Path\To\File.txt"
```

Notice that your file might have started another process and some research might be required.

## Identifying a proxy PEM

```bash
# List all root certs:
Get-ChildItem -Path Cert:\LocalMachine\Root

# Export a specific one:
$cert = Get-ChildItem -Path Cert:\LocalMachine\Root | Where-Object {
    $_.Subject -like "*<company-name-generally>*"
}
Export-Certificate -Cert $cert -FilePath "proxy.pem"
```

## Enabling OpenSSH server {#sec-enabling-openssh-server}

This will require administrator privileges; open PowerShell as administrator and run `winver` to check your Windows version. If it is 10 or higher (Pro/Enterprise), or Windows Server 2019 or higher, you can enable OpenSSH server. Windows Home does not support the service. Use the following instructions.

Check for possibility to install OpenSSH server:

```bash
Get-WindowsCapability -Online | ? Name -like 'OpenSSH*'
```

Output should be something like this:

```text
OpenSSH.Client~~~~0.0.1.0   Installed
OpenSSH.Server~~~~0.0.1.0   NotPresent
```

If Server appears as `NotPresent`, install it (it will take a while):

```bash
Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0
```

Finally, start and enable the service:

```bash
Start-Service sshd
Set-Service -Name sshd -StartupType Automatic
```

Check that it is installed and running:

```bash
Get-WindowsCapability -Online | ? Name -like 'OpenSSH*'
```

Something like this should be displayed:

```text
Name  : OpenSSH.Client~~~~0.0.1.0
State : Installed
```

Try to connect to the server from another machine using `ssh <username>@<ip-address>`; if it does not work, before trying the following, open settings (in the server) and check `Settings → Network & Internet → Properties → Network profile` is set to `Private` and not `Public`.

Some troubleshooting ideas:

- Check that the service is running:

```bash
Get-Service sshd
# Status   Name               DisplayName
# ------   ----               -----------
# Running  sshd               OpenSSH SSH Server
```

- Check the actual IPv4 of the machine:

```bash
ipconfig
```

- Check that the server is listening on port 22:

```bash
netstat -an | findstr ":22"
#   TCP    0.0.0.0:22             0.0.0.0:0              LISTENING
#   TCP    [::]:22                [::]:0                 LISTENING
```

- Check the firewall rules:

```bash
Get-NetFirewallRule -DisplayName "*ssh*"
# New-NetFirewallRule -Name "OpenSSH-Server-In-TCP" `
#   -DisplayName "OpenSSH Server (Inbound)" `
#   -Enabled True -Direction Inbound -Protocol TCP -Action Allow -LocalPort 22
```

- Check the configuration file of the server; if you have a problem with IPv6, for example, you can change `AddressFamily` to `any` or `inet`:

```bash
notepad 'C:\ProgramData\ssh\sshd_config'
# AddressFamily any

# After any change, remember to restart the service:
Restart-Service sshd
Get-Service sshd
```
