# AlmaLinux installation

## Preliminary steps

- [ ] Change keyboard for compatible type (US, intl, with dead keys)
- [ ] Set correct timezone for avoiding later conflicts
- [ ] Set user name and select administrator privileges
- [ ] Configure as workstation with desired extra packages
- [ ] Connect to the internet before installation

## Fresh installation setup

First of all, enable passwordless system management:

``` bash
sudo visudo
# walter ALL=(ALL) ALL
# Defaults:walter !authenticate
```

Ensure the system is fully up-to-date:

``` bash
sudo dnf update -y
```

Install useful tools:

``` bash
sudo dnf install -y btop screen terminator
sudo dnf install -y curl wget pandoc
```

Edit `~/.config/user-dirs.dirs` to my style:

``` conf
XDG_DESKTOP_DIR="$HOME/"
XDG_DOWNLOAD_DIR="$HOME/Downloads"
XDG_TEMPLATES_DIR="$HOME/.templates"
XDG_PUBLICSHARE_DIR="$HOME/.public"
XDG_DOCUMENTS_DIR="$HOME/"
XDG_MUSIC_DIR="$HOME/"
XDG_PICTURES_DIR="$HOME/"
XDG_VIDEOS_DIR="$HOME/"
```

Enable fractional scaling if needed:

``` bash
gsettings set org.gnome.mutter \
    experimental-features "['scale-monitor-framebuffer']"
gsettings set org.gnome.mutter \
    experimental-features "['scale-monitor-framebuffer', 'xwayland-native-scaling']"
```

Enable RPD connection

``` bash
# Enable repositories
sudo dnf config-manager --set-enabled crb
sudo dnf install epel-release -y

# Install XRDP (not provided directly by repo):
# sudo dnf install xrdp -y
sudo dnf install -y \
    https://repo.almalinux.org/almalinux/9/AppStream/x86_64/os/Packages/tigervnc-license-1.15.0-6.el9_7.noarch.rpm
sudo dnf install -y \
    https://repo.almalinux.org/almalinux/9/AppStream/x86_64/os/Packages/tigervnc-server-minimal-1.15.0-6.el9_7.x86_64.rpm
sudo dnf install -y \
    https://dl.fedoraproject.org/pub/epel/9/Everything/x86_64/Packages/x/xrdp-0.10.4-2.el9.x86_64.rpm

# Manage service:
sudo systemctl start xrdp
sudo systemctl enable xrdp
sudo systemctl status xrdp

# Enable port:
sudo firewall-cmd --permanent --add-port=3389/tcp
sudo firewall-cmd --reload
sudo firewall-cmd --list-ports

# Configure GNOME session:
sudo vim /etc/xrdp/startwm.sh
# #!/bin/bash
# unset DBUS_SESSION_BUS_ADDRESS
# unset XDG_RUNTIME_DIR
# exec /usr/bin/gnome-session

sudo setsebool -P xrdp_can_connect_network 1

# Debug SELinux
sudo ausearch -m avc
sudo sealert -a /var/log/audit/audit.log
```

Disable any *stand-by* method (required for RDP):

``` bash
systemctl mask \
    sleep.target \
    suspend.target \
    hibernate.target \
    hybrid-sleep.target
```
Install Microsoft Edge:

``` bash
sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
sudo dnf config-manager --add-repo https://packages.microsoft.com/yumrepos/edge
sudo dnf update --refresh
sudo dnf install microsoft-edge-stable
```

Install [neovim](https://neovim.io/doc/install/) (the version in dnf is outdated):

``` bash
wget -O ~/Apps/nvim-linux-x86_64.tar.gz \
    https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz

tar -xvzf "~/Apps/nvim-linux-x86_64.tar.gz" -C "~/Apps/"
mkdir -p "~/.local/bin"
ln -s "$(realpath $HOME)/Apps/nvim-linux-x86_64/bin/nvim" "~/.local/bin/nvim"
```

## Dealing with NVidia

Install [NVidia drivers](https://almalinux.org/blog/2025-08-06-announcing-native-nvidia-suport/):

```bash
dnf install almalinux-release-nvidia-driver
dnf install nvidia-open

# Test everything went fine:
sudo modprobe nvidia-drm
lspci | grep -i nvidia
```

If the above worked, then install CUDA support:

```bash
dnf install nvidia-driver-cuda

# Test everything went fine:
nvidia-smi
```

::: {.callout-warning title="NVidia debugging"}
Unfortunatelly NVidia installation is never trivial. During the quest to get it working, the following summarize the most important commands I had to run. Just disabling secure boot did not solve the proble, nor installing the kernel headers and development version. It was probably the regeneration of `initramfs` that got my system working.

``` bash
# Check for secure boot mode:
mokutil --sb-state

# Check driver versions:
modinfo nvidia | grep version
modinfo nvidia-drm | grep version

# Check which driver owns the GPU:
lspci -k | grep -A 2 -i nvidia

# Install compatible kernel versions:
sudo dnf install kernel-headers-$(uname -r)
sudo dnf install kernel-devel-$(uname -r)

# Regenerate initramfs:
sudo dracut --regenerate-all --force

# Reinstall driver
sudo dnf reinstall nvidia-open nvidia-driver-cuda
```
:::

Install NVidia container support:

``` bash
sudo dnf install nvidia-container-toolkit
```

## Development environment

Install VS Code:

``` bash
printf "[vscode]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode/\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc\nmetadata_expire=1h" | sudo tee /etc/yum.repos.d/vscode.repo
sudo dnf install code
```

Clone Majordome and link VS Code settings:

``` bash
cd local/data/vscode/user-data/User/
ln -s "$(realpath $PWD)/settings.json" "~/.config/Code/User/settings.json"
```

Install container tools:

``` bash
sudo dnf install -y podman fakeroot
sudo dnf install -y epel-release
sudo dnf install -y apptainer-suid
```

Install development tools:

``` bash
# Required for mpich/openmpi module support
sudo dnf install environment-modules
source /usr/share/Modules/init/bash

sudo dnf install git gh make cmake
sudo dnf install -y gcc-g++ gcc-gfortran python3-devel
sudo dnf install -y mpich-devel openmpi-devel
```

Install [Rust](https://rust-lang.org/tools/install/) and [rust-analyzer](https://rust-analyzer.github.io/book/installation.html):

``` bash
# Select nightly toolchain for rust-analyzer support:
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

rustup toolchain install nightly
rustup component add rust-analyzer --toolchain nightly
```

Install [Quarto](https://quarto.org/docs/download/tarball.html?version=1.8.27&idPrefix=download):

``` bash
quarto_version=1.8.27
quarto_releases="https://github.com/quarto-dev/quarto-cli/releases"
quarto_archive="quarto-${quarto_version}-linux-amd64.tar.gz"

wget -O "~/Apps/${quarto_archive}" \
    "${quarto_releases}/download/v${quarto_version}/${quarto_archive}"

tar -xvzf "~/Apps/${quarto_archive}" -C "~/Apps/"
mkdir -p "~/.local/bin"
ln -s "$(realpath $HOME)/Apps/quarto-${quarto_version}/bin/quarto" "~/.local/bin/quarto"

quarto check
```

Install LaTeX:

``` bash
wget https://mirrors.ircam.fr/pub/CTAN/systems/texlive/tlnet/install-tl-unx.tar.gz
tar -xzf install-tl-unx.tar.gz
cd install-tl-*/
sudo ./install-tl

echo 'export PATH="/usr/local/texlive/2025/bin/x86_64-linux:${PATH}"' >> ~/.bashrc
source ~/.bashrc
tlmgr update --all

# Add /usr/local/texlive/2025/texmf-dist/doc/man to MANPATH.
# Add /usr/local/texlive/2025/texmf-dist/doc/info to INFOPATH.
# Most importantly, add /usr/local/texlive/2025/bin/x86_64-linux
# to your PATH for current and future sessions.
```

```{python}
zettlr_github="https://github.com/Zettlr/Zettlr"
zettlr_version="4.1.0"
zettlr_archive="Zettlr-${zettlr_version}-x86_64.rpm"

wget -O "${HOME}/Apps/${zettlr_archive}" \
    "${zettlr_github}/releases/download/v${zettlr_version}/${zettlr_archive}"

sudo dnf install -y "${HOME}/Apps/${zettlr_archive}"
```

Install [draw.io](https://github.com/jgraph/drawio-desktop):

``` bash
drawio_version="29.3.0"
drawio_github="https://github.com/jgraph/drawio-desktop"
drawio_archive="drawio-x86_64-${drawio_version}.rpm"

wget -O "${HOME}/Apps/${drawio_archive}" \
    "${drawio_github}/releases/download/v${drawio_version}/${drawio_archive}"

sudo dnf install -y "${HOME}/Apps/${drawio_archive}"
```

## Simulation tools

``` bash
sudo dnf install cgnslib
```

``` bash
wget https://github.com/su2code/SU2/releases/download/v8.4.0/SU2-v8.4.0-linux64-mpi.zip

unzip SU2-v8.4.0-linux64-mpi.zip -d SU2
unzip SU2/linux64-mpi.zip -d SU2
rm SU2/linux64-mpi.zip

echo "export PATH=\"$(realpath $PWD)/SU2/bin:\${PATH}\"" >> ~/.bashrc
```
