# Containerized services

Notice that the following services are mostly GPU reliant and being able to run CUDA images is *almost* a prerequisite. That is because performance in CPU can be so boringly slow that becomes prohibitive for anything other than learning how to create services. Nvidia images compatible with your driver (for adapting the provided `Containerfile`'s) are found [here](https://hub.docker.com/r/nvidia/cuda). If you are new to *containerization* technologies, please refer to the dedicated [chapter @sec-using-containers] before continuing here.

## Ollama LLMs

In this section we explore containerized deployment of large language models (LLMs) using [Ollama](https://ollama.com/) for local deployment. For learing more about LLMs, the reader is referred to the following links:

-   Platforms:

    -   [Ollama](https://ollama.com/)
    -   [HuggingFace](https://huggingface.co/)

-   Models:

    -   [llama3.1](https://ollama.com/library/llama3.1)
    -   [mistral-nemo](https://ollama.com/library/mistral-nemo)

-   Packages:

    -   [ollama](https://github.com/ollama/ollama-python)
    -   [haystack](https://docs.haystack.deepset.ai/docs/intro)
    -   [weaviate](https://docs.weaviate.io/weaviate/quickstart)

### Deploying in RHEL

``` bash
# https://developer.nvidia.com/cuda-downloads

# Identify NVIDIA driver
nvidia-smi

# Identify RHEL version
cat /etc/redhat-release
# or rpm -q redhat-release

# Add corresponding repo/toolkit
BASE=https://developer.download.nvidia.com/compute/cuda/repos
REPO="${BASE}/rhel9/x86_64/cuda-rhel9.repo"
dnf config-manager --add-repo="${REPO}"
dnf clean all

dnf -y install cuda-toolkit-13-0
dnf install -y cuda-toolkit-13-0

dnf install -y cuda-driver-devel-12-8
dnf install -y cuda-toolkit-12-8
```

## ParticleAnalyzer

- [Repository](https://github.com/rybakov-ks/ParticleAnalyzer)

``` bash
# -p 5000:5000 -> not required
docker run -it --network host --gpus all particle-devel:latest
```

## Taiga

-   [GitHub: docker-taiga](https://github.com/docker-taiga/taiga)
-   [Docs: production](https://docs.taiga.io/setup-production.html#_get_repository)
-   [Taiga 30min setup](https://community.taiga.io/t/taiga-30min-setup/170)